/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#37466c",
        "primary-fixed": "#dae2ff",
        "surface-container": "#f0eded",
        "surface-bright": "#fbf9f8",
        "outline": "#737784",
        "on-tertiary-fixed-variant": "#802900",
        "primary-fixed-dim": "#b1c5ff",
        "error": "#ba1a1a",
        "on-primary-container": "#a5bdff",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#00419e",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#0047ab",
        "surface-container-highest": "#e4e2e1",
        "surface-container-high": "#eae8e7",
        "on-tertiary-container": "#ffaa8a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0f0",
        "tertiary-container": "#8b2e01",
        "secondary-container": "#c1d1ff",
        "on-error-container": "#93000a",
        "tertiary": "#651f00",
        "on-surface-variant": "#434653",
        "inverse-surface": "#303030",
        "inverse-primary": "#b1c5ff",
        "secondary": "#4e5e85",
        "on-surface": "#1b1c1c",
        "background": "#fbf9f8",
        "surface-variant": "#e4e2e1",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#ffdbcf",
        "surface": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59a",
        "surface-tint": "#2559bd",
        "on-primary-fixed": "#001946",
        "on-secondary": "#ffffff",
        "primary": "#00327d",
        "on-secondary-container": "#4a5980",
        "secondary-fixed": "#dae2ff",
        "on-background": "#1b1c1c",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b6c6f3",
        "on-tertiary-fixed": "#380d00",
        "outline-variant": "#c3c6d5",
        "on-secondary-fixed": "#081a3e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "32px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}

